:-use_module(library(clpfd)).
:-use_module(library(lists)).
:-use_module(library(random)).
:-use_module(library(system)).
:-consult(utilities).
:-consult(board).
:-consult(problems).
:-consult(solve).
:-consult(kenken).
